[build]
  command = "pnpm build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "remix watch"
  port = 9000
  autoLaunch = false

# [functions]
#   node_bundler = "esbuild"

[functions.server]
  included_files = ["app/routes/**/*.mdx"]

[functions."data-members"]
  external_node_modules = ["shiki"]
  included_files = ["members/**/*.{js,json}"]

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[redirects]]
  from = "/members/map"
  to = "/members"
  status = 301

[[redirects]]
  from = "/netlify-forms"
  to = "/"
  status = 200

[[redirects]]
  from = "/report-coc-violation-success"
  to = "/"
  status = 200

[[redirects]]
  from = "/sponsorship"
  to = "https://github.com/sponsors/Virtual-Coffee"
  status = 302

[[redirects]]
  from = "/brownbag-idea"
  to = "/lunch-and-learn-idea"
  status = 301
  force = true

[[redirects]]
  from = "/brownbag-idea-thanks"
  to = "/lunch-and-learn-idea-thanks"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources"
  to = "/resources"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/oss-maintainer-checklist"
  to = "/resources/open-source/oss-maintainer-checklist"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/oss-writing-issues"
  to = "/resources/open-source/oss-writing-issues"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/guide-to-vc"
  to = "/resources/virtual-coffee/guide-to-vc"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/join-virtual-coffee"
  to = "/resources/virtual-coffee/join-virtual-coffee"
  status = 301
  force = true

[[redirects]]
  from = "/member-resources/slack-channel-guide"
  to = "/resources/virtual-coffee/slack-channel-guide"
  status = 301
  force = true

[[redirects]]
  from = "/resources/open-source/oss-writing-issues"
  to = "/resources/open-source/contributor-guide#guide-to-writing-issues"
  status = 301
  force = true

[[redirects]]
  from = "/resources/open-source/oss-maintainer-checklist"
  to = "/resources/open-source/maintainer-guide"
  status = 301
  force = true

[[redirects]]
  from = "/join-coffee"
  query = {day = ":day", code = ":code"}
  to = "/.netlify/functions/join-coffee"
  status = 200

[[redirects]]
  from = "/join-slack"
  query = { code = ":code"}
  to = "/.netlify/functions/join-slack"
  status = 200

[[redirects]]
  from = "/plausible/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/plausible/api/event"
  to = "https://plausible.io/api/event"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200